version: '3'

services:
  elysium-node:
    container_name: elysium-node
    image: intellicoworks/elysium:latest
    ports:
      - 30333:30333 # p2p port
      - 127.0.0.1:9933:9933 # rpc port
      - 127.0.0.1:9944:9944 # ws port
    volumes:
      - ./chain-data:/data
    command: [
      "--name","elysium-node",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors", "all",
      "--unsafe-rpc-external",
      "--rpc-methods=Safe",
      "--unsafe-ws-external",
      "--prometheus-external",
      "--node-key", "YOUR NODE KEY",
      "--chain", "./elysiumSpecRaw.json",
      "--bootnodes", "/ip4/IP-ADDRESS/tcp/30333/p2p/PEER-ID",
      "--offchain-worker","always",
      "--validator"
    ]
